### ISSUE TITLE
Add script to disable SimpleSAMLphp module for local testing

### ISSUE THREAD

**Issue by timurtripp** [CuBoulder/tiamat10-project-template#2]
`/app/vendor/bin/drush pmu simplesamlphp_auth`

The Drupal 9 project template has this, the Drupal 10 project template is missing it.

**Comment by jcsparks** [comment]
It is already in there @TeddyBearX - make sure you've got the latest version.  Let me know if it's not working for you on site-install.

**Comment by timurtripp** [comment]
Resolved via CuBoulder/tiamat10-project-template#3
